server:
  port: ${SERVER_PORT}
spring:
  liquibase:
      change-log: classpath:/db/db.changelog-master.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?currentSchema=${DB_SCHEMA}"
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
kafka:
  producer:
    user-location:
      topic: "v1.user-location"
      partitions: 2
      replicas: 2
    user-interaction:
      topic: "v1.user-interaction"
      partitions: 2
      replicas: 2
  consumer:
    group-id: ${KAFKA_CONSUMER_GROUP_ID}
    notification-message:
      topic: "v1.notification-message"
jwt:
  secret-key: 54497fabdc224a81d3bfe6c522b141ff8969730ea18f398efbc36f3b7b348dbb
  access-token:
    lifetime: 1d
  refresh-token:
    lifetime: 30d
api:
  client:
    incident:
      rest:
        host: ${LOCATION_TRACKER_HOST}
        port: ${LOCATION_TRACKER_PORT}